"""Initial migration

Revision ID: 8b7c505a696a
Revises: 
Create Date: 2026-03-10 17:15:00.923144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7c505a696a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_app_configurations_id', table_name='app_configurations')
    op.drop_index('ix_app_configurations_key', table_name='app_configurations')
    op.drop_table('app_configurations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_configurations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='app_configurations_pkey')
    )
    op.create_index('ix_app_configurations_key', 'app_configurations', ['key'], unique=False)
    op.create_index('ix_app_configurations_id', 'app_configurations', ['id'], unique=False)
    # ### end Alembic commands ###
