"""Initial migration

Revision ID: 8b7c505a696a
Revises: 
Create Date: 2026-03-10 17:15:00.923144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7c505a696a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_connections_id'), 'ai_connections', ['id'], unique=False)
    op.create_index(op.f('ix_ai_connections_name'), 'ai_connections', ['name'], unique=True)
    
    op.create_table('document_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('full_response_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_reviews_content_hash'), 'document_reviews', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_reviews_filename'), 'document_reviews', ['filename'], unique=False)
    op.create_index(op.f('ix_document_reviews_id'), 'document_reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_reviews_id'), table_name='document_reviews')
    op.drop_index(op.f('ix_document_reviews_filename'), table_name='document_reviews')
    op.drop_index(op.f('ix_document_reviews_content_hash'), table_name='document_reviews')
    op.drop_table('document_reviews')
    op.drop_index(op.f('ix_ai_connections_name'), table_name='ai_connections')
    op.drop_index(op.f('ix_ai_connections_id'), table_name='ai_connections')
    op.drop_table('ai_connections')
    # ### end Alembic commands ###
